baseurl = "https://www.brendanburkhart.com"
title = "Brendan Burkhart"
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Brendan Burkhart" # Author's name.
    info = "Student, programmer, runner" # Author's job title or info.
    description = "Brendan Burkhart's personal website" # Site description.
    keywords = "developer,personal,robots,backend" # Site keywords.
    avatarurl = "img/profile.jpg" # Contain the path of the optionnal avatar in the static folder.

    #footercontent = "Hey people"
    #fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    #fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    #snsShare = true # new add

    # thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/brendanburkhart/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/brendan-burkhart-362a6b166/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "projects/list"
[[menu.main]]
    name = "Robotics"
    weight = 3
    url = "robotics"
[[menu.main]]
    name = "Resume"
    weight = 4
    url  = "resume.pdf"
